# Generated by Django 6.0.3 on 2026-03-09 23:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Triage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('symptom1', models.CharField(max_length=100)),
                ('symptom2', models.CharField(max_length=100)),
                ('symptom3', models.CharField(blank=True, max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('duration', models.IntegerField(help_text='Duração em dias')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AIanalyses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField()),
                ('resposta', models.JSONField()),
                ('model', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('triage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analise', to='triage.triage')),
            ],
        ),
    ]
