from rest_framework import viewsets
from .serializers import AIanalysesSerializer, TriageSerializer
from .models import AIanalyses, Triage
from .services.ai_service import GeminiService
from .services.maps_service import MapsService
from rest_framework.views import APIView
from rest_framework.response import Response
from .throttles import TriageRateThrottle


class TriageViewSet(viewsets.ModelViewSet):
    """
        API endpoint for medical triage.

        POST /triage/
        Creates a new medical triage based on patient symptoms.

        After the triage is created, the system automatically sends the data to the Gemini AI service 
        to generate a risk analysis.

        Example request:

        {
            "age": 19,
            "symptom1": "fever",
            "symptom2": "cough",
            "symptom3": "",
            "description":"pain when breathing",
            "duration": 2

        }
    """
    queryset = Triage.objects.all()
    serializer_class = TriageSerializer
    http_method_names = ['post','get'] # GET Temporary
    throttle_classes = [TriageRateThrottle]

    def perform_create(self, serializer):
        """
        Save triages data and trigger the AiAnalysis.
        """
 
        triage = serializer.save()
 
        service = GeminiService()
 
        resposta = service.analise(triage)
 
        AIanalyses.objects.create(
        triage=triage,
        prompt="triagem médica",
        resposta=resposta,
        model="gemini-3-flash-preview"
        )

        

class NearbyHospitalsView(APIView):
    """
        Nearby hospitals endpoint.

        Returns hospitals near the provided geographic coordinates.
        The hospitals are retrieved using the Google Maps API.

        Query parameters:
        - lat (float): Latitude of the user location
        - lng (float): Longitude of the user location
        - speciality (string): Medical speciality used to filter hospitals

        Example request:

        GET /hospitals/nearby/?lat=-XX.XXXX&lng=-XX.XXXX&speciality=cardiology

        Example response:

        [
            {
                "name": "Hospital Santa Cruz",
                "address": "Rua Santa Cruz, São Paulo",
                "maps_link": "https://maps.google.com/..."
            }
        ]
        """

    def get(self, request):
        """
        Retrieves nearby hospitals based on location and speciality.
        """
        lat = request.query_params.get("lat")
        lng = request.query_params.get("lng")
        speciality = request.query_params.get("speciality")

        service = MapsService()

        hospitals = service.search_hospital(lat, lng, speciality)

        return Response(hospitals)


# #class for tests !!!
# class NearbyHospitalsView(APIView):
 
#     def get(self, request):
 
#         lat = -xx.xxxxxxx
#         lng = -xx.xxxxxxx
#         speciality = 'Clinica Geral'
#         service = MapsService()
 
#         hospitals = service.search_hospital(lat,lng,speciality)
 
#         return Response(hospitals)


class AiAnalysesViewSet(viewsets.ModelViewSet):
    """
    AI analyses endpoint.

    Return AI-generated analyses for medical triages.

    This endpoint retrieves analyses generated by the Gemini AI
    after a triage is created.

    Query parameters:
    - triage (integer): ID of the triage used to filter analyses.

    If the triage paramter is provided, the endpoint returns only the analysis related to that triage.

    Example request:

    GET /analysis/?triage=7

    Example response:

    [
        {
            "id": 1,
            "prompt": "triagem médica",
            "resposta": {
                "risco": "moderado",
                "possiveis_causas": [
                    "Gripe (Influenza)",
                    "COVID-19",
                    "Resfriado comum",
                    "Pneumonia"
                ],
                "especialidades_recomendadas": [
                    "Clínico Geral",
                    "Infectologista"
                ],
                "recomendacoes": "Mantenha repouso e hidratação constante. Monitore a temperatura corporal. Recomenda-se buscar avaliação médica em uma unidade de pronto atendimento para diagnóstico diferencial, especialmente se houver falta de ar, dor no peito ou persistência da febre."
            },
            "model": "gemini-3-flash-preview",
            "created_at": "2026-03-10T11:55:39.167885-03:00",
            "triage": 6
        }
    ]
    
    """
    queryset = AIanalyses.objects.all()
    serializer_class = AIanalysesSerializer
    http_method_names = ['get']

    def get_queryset(self):
        """
        Filters analyses by triage ID
        """
        queryset = AIanalyses.objects.all()
        triage_id = self.request.query_params.get('triage')

        if triage_id:
            queryset = queryset.filter(triage_id=triage_id)
        
        return queryset

